python3 /home/lupones/simplot//simplot.py -g 1 2 -o output2.pdf --size 16 5 --rect 0 0.25 1 1 \
--plot '{legend_options: {fontsize: 22, borderpad: 0.2, labelspacing: 0.1, loc: center, bbox_to_anchor: [0.5, -0.54], ncol: 3, columnspacing: 1, fancybox: True, frameon: False}, font: {size: 25}, ymax: 10, ymin: 0, ymajorlocator: ["MultipleLocator", {base: 2}], xmax: 266, xmin: 0, xmajorlocator: ["MultipleLocator", {base: 38}], kind: l, colormap: Paired_r, numcolors: 9, color: ["#b15928"], datafile: /home/lupones/XPL3/outputCSVfiles/europar//criticalAlone/resultTables/bwaves-calculix-dealII-gromacs-leslie3d-sjeng-xalancbmk-omnetpp/00_bwaves-intervalDataTable.csv, index: 0, cols: [6], ylabel: MPKI-L3, xlabel: Interval, ymin: 0, labels: [bwaves]}' \
--plot '{legend_options: {fontsize: 22, borderpad: 0.2, labelspacing: 0.1, loc: center, bbox_to_anchor: [0.5, -0.54], ncol: 3, columnspacing: 1, fancybox: True, frameon: False}, ymax: 10, ymin: 0, ymajorlocator: ["MultipleLocator", {base: 2}], xmax: 266, xmin: 0, xmajorlocator: ["MultipleLocator", {base: 38}], axnum: 0, kind: l, colormap: Paired_r, numcolors: 9, color: ["#ffff99"], datafile: /home/lupones/XPL3/outputCSVfiles/europar//criticalAlone/resultTables/bwaves-calculix-dealII-gromacs-leslie3d-sjeng-xalancbmk-omnetpp/01_calculix-intervalDataTable.csv, index: 0, cols: [6], ylabel: MPKI-L3, xlabel: Interval, labels: [calculix]}' \
--plot '{legend_options: {fontsize: 22, borderpad: 0.2, labelspacing: 0.1, loc: center, bbox_to_anchor: [0.5, -0.54], ncol: 3, columnspacing: 1, fancybox: True, frameon: False}, ymax: 10, ymin: 0, ymajorlocator: ["MultipleLocator", {base: 2}], xmax: 266, xmin: 0, xmajorlocator: ["MultipleLocator", {base: 38}], axnum: 0, kind: l, colormap: Paired_r, numcolors: 9, color: ["#cab2d6"], datafile: /home/lupones/XPL3/outputCSVfiles/europar//criticalAlone/resultTables/bwaves-calculix-dealII-gromacs-leslie3d-sjeng-xalancbmk-omnetpp/02_dealII-intervalDataTable.csv, index: 0, cols: [6], ylabel: MPKI-L3, xlabel: Interval, labels: [dealII]}' \
--plot '{legend_options: {fontsize: 22, borderpad: 0.2, labelspacing: 0.1, loc: center, bbox_to_anchor: [0.5, -0.54], ncol: 3, columnspacing: 1, fancybox: True, frameon: False}, ymax: 10, ymin: 0, ymajorlocator: ["MultipleLocator", {base: 2}], xmax: 266, xmin: 0, xmajorlocator: ["MultipleLocator", {base: 38}], axnum: 0, kind: l, colormap: Paired_r, numcolors: 9, color: ["#fdbf6f"], datafile: /home/lupones/XPL3/outputCSVfiles/europar//criticalAlone/resultTables/bwaves-calculix-dealII-gromacs-leslie3d-sjeng-xalancbmk-omnetpp/03_gromacs-intervalDataTable.csv, index: 0, cols: [6], ylabel: MPKI-L3, xlabel: Interval, labels: [gromacs]}' \
--plot '{legend_options: {fontsize: 22, borderpad: 0.2, labelspacing: 0.1, loc: center, bbox_to_anchor: [0.5, -0.54], ncol: 3, columnspacing: 1, fancybox: True, frameon: False}, ymax: 10, ymin: 0, ymajorlocator: ["MultipleLocator", {base: 2}], xmax: 266, xmin: 0, xmajorlocator: ["MultipleLocator", {base: 38}], axnum: 0, kind: l, colormap: Paired_r, numcolors: 9, color: ["#e31a1c"], datafile: /home/lupones/XPL3/outputCSVfiles/europar//criticalAlone/resultTables/bwaves-calculix-dealII-gromacs-leslie3d-sjeng-xalancbmk-omnetpp/04_leslie3d-intervalDataTable.csv, index: 0, cols: [6], ylabel: MPKI-L3, xlabel: Interval, labels: [leslie3d]}' \
--plot '{legend_options: {fontsize: 22, borderpad: 0.2, labelspacing: 0.1, loc: center, bbox_to_anchor: [0.5, -0.54], ncol: 3, columnspacing: 1, fancybox: True, frameon: False}, ymax: 10, ymin: 0, ymajorlocator: ["MultipleLocator", {base: 2}], xmax: 266, xmin: 0, xmajorlocator: ["MultipleLocator", {base: 38}], axnum: 0, kind: l, colormap: Paired_r, numcolors: 9, color: ["#33a02c"], datafile: /home/lupones/XPL3/outputCSVfiles/europar//criticalAlone/resultTables/bwaves-calculix-dealII-gromacs-leslie3d-sjeng-xalancbmk-omnetpp/05_sjeng-intervalDataTable.csv, index: 0, cols: [6], ylabel: MPKI-L3, xlabel: Interval, labels: [sjeng]}' \
--plot '{legend_options: {fontsize: 22, borderpad: 0.2, labelspacing: 0.1, loc: center, bbox_to_anchor: [0.5, -0.54], ncol: 3, columnspacing: 1, fancybox: True, frameon: False}, ymax: 10, ymin: 0, ymajorlocator: ["MultipleLocator", {base: 2}], xmax: 266, xmin: 0, xmajorlocator: ["MultipleLocator", {base: 38}], axnum: 0, kind: l, colormap: Paired_r, numcolors: 9, color: ["#1f78b4"], datafile: /home/lupones/XPL3/outputCSVfiles/europar//criticalAlone/resultTables/bwaves-calculix-dealII-gromacs-leslie3d-sjeng-xalancbmk-omnetpp/06_xalancbmk-intervalDataTable.csv, index: 0, cols: [6], ylabel: MPKI-L3, xlabel: Interval, labels: [xalancbmk]}' \
--plot '{legend_options: {}, ymax: 10, ymin: 0, ymajorlocator: ["MultipleLocator", {base: 2}], xmax: 266, xmin: 0, xmajorlocator: ["MultipleLocator", {base: 38}], axnum: 0, kind: l, colormap: Paired_r, numcolors: 9, color: ["#a6cee3"], datafile: /home/lupones/XPL3/outputCSVfiles/europar//criticalAlone/resultTables/bwaves-calculix-dealII-gromacs-leslie3d-sjeng-xalancbmk-omnetpp/07_omnetpp-intervalDataTable.csv, index: 0, cols: [6], ylabel: MPKI-L3, xlabel: Interval, labels: [omnetpp]}' \
--plot '{legend_options: {fontsize: 22, borderpad: 0.2, labelspacing: 0.1, loc: center, bbox_to_anchor: [-0.15, -0.54], ncol: 4, columnspacing: 1, fancybox: True, frameon: False}, font: {size: 25}, xmax: 266, xmin: 0, xmajorlocator: ["MultipleLocator", {base: 38}], kind: stackedarea, colormap: Paired_r, numcolors: 8, color: [d0, d1, d2, d3, d4, d5, d6, d7], datafile: /home/lupones/XPL3/outputCSVfiles/europar//criticalAlone/resultTables/bwaves-calculix-dealII-gromacs-leslie3d-sjeng-xalancbmk-omnetpp/LLC_occup_apps_data_table.csv, index: 0, ylabel: LLC Occup (MB), xlabel: Interval, ymax: 20, ymin: 0}'




#python3 /home/lupones/simplot//simplot.py -g 1 1 -o /home/lupones/XPL3/outputCSVfiles/europar/graphs/LLC-criticalAlone-bwaves-calculix-dealII-gromacs-leslie3d-sjeng-xalancbmk-omnetpp-graph.pdf --size 8 5 --rect 0 0.25 0.97 1 \

#b15928
#ffff99
#cab2d6
#fdbf6f
#e31a1c
#33a02c
#1f78b4
#a6cee3

